name: 🚀 Release

on:
  push:
    branches:
      - test-release

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # main

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: latest

      - name: 🚀 Release on jsr
        run: |
          deno publish
