name: 🧪 Test and 🚀 Release

on:
  push:
    branches:
      - main
      - beta
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      # Necessary for semantic-release
      contents: write
      issues: write
      pull-requests: write
      # Necessary for npm publish --provenance
      # See https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow
      id-token: write
      packages: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # main

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@5e2628c959b9ade56971c0afcebbe5332d44b398 # main
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: 🗄 Cache node_modules
        id: cache-node_modules
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4 # main
        with:
          path: "**/node_modules"
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: 🗄 Cache .eslintcache
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4 # main
        with:
          path: .eslintcache
          key: eslintcache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: 🔍 Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts --prefer-offline --no-audit

      - name: 🧪 Run tests
        run: |
          npm test
        env:
          CI: true

      - name: ⬆️ Upload coverage report
        uses: coverallsapp/github-action@e7f4f977bd3dba07a6fda03be3053f1658992446 # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Release preview
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/beta' }}
        # Call to npm publish --dry-run is currently necessary, see https://github.com/stackblitz-labs/pkg.pr.new/issues/320
        run: |
          npm publish --dry-run
          npx pkg-pr-new publish

      - name: 🚀 Release on npm and jsr
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release
