name: 🧪 Test and 🚀 Release

on:
  push:
    branches:
      - test-release

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      # Necessary for semantic-release
      contents: write
      issues: write
      pull-requests: write
      # Necessary for npm publish --provenance
      # See https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow
      id-token: write
      packages: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # main

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@774c1d62961e73038a114d59c8847023c003194d # main
        with:
          node-version-file: ".tool-versions"

      - name: 🔍 Install dependencies
        run: |
          npm ci --ignore-scripts --prefer-offline --no-audit

      - name: 🚀 Release on npm and jsr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx jsr publish
